### ISSUE TITLE
any luck getting this to work?

### ISSUE THREAD

**Issue by NeilHanlon** [CyberPixel44/guess-poly-rolcode#1]
Hey there :) Thanks for the work on this. I admit I don't fully understand the maths behind the scenes here, but the code (appears) to work--in that if I give it my file of collected codes, it has eventually spit out a guess for me to try. Unfortunately, I get the same "erro" message when I try to enter this into the unlock screen and it appears that I'm not getting any new codes (or at least, have not for quite some time). I'm guessing that there is some sort of protection built in to prevent getting too many sequential codes at once.

In case it's helpful:

```
-----------------------------------------------------------------
Degree 1:
Decimal values: [2620048414, 2279923664, 3972445426, 3114131881, 2394478220]
Polynomial estimation function: y = 2761285172.299999 + 38306782.90000012x^1
r^2 value: 0.007676420355987701

-----------------------------------------------------------------
Degree 2:
Decimal values: [2620048414, 2279923664, 3972445426, 3114131881, 2394478220]
Polynomial estimation function: y = 1106338607.799992 + -236420937.7857155x^2 + 1456832409.614293x^1
r^2 value: 0.4170382025273417

-----------------------------------------------------------------
Degree 3:
Decimal values: [2620048414, 2279923664, 3972445426, 3114131881, 2394478220]
Polynomial estimation function: y = 3757919887.000004 + -157832219.00000048x^3 + 1184069033.2142901x^2 + -2268007958.7857265x^1
r^2 value: 0.6046936622961696

 statusOutput of command for decimal 2991126112 is equal to B248F660 with binary 10110010010010001111011001011111
```

```
$ cat samples
9C2AC41E
87E4DFD0
ECC6B4F2
B99DE1A9
8EB8D68C
```

**Comment by CyberPixel44** [comment]
Hiya! Admittedly, this whole project was an attempt at reverse engineering the code for the Explorer QRZ. I feel like this has some potential to go further, but this is where I stop as I do not see any further paths. Some patterns exist, but I can't get it to work. My hope in publishing this test is to maybe give other, more smarter, people some clues or a foundation to try on their own. Good luck, and please let us know if you get anywhere further!
